### ISSUE TITLE
bytelen|len acceps float inputs

### ISSUE THREAD

**Issue by KernelPryanic** [graph-guard/gqt#13]
GQT allows the following expressions to pass the parsing:
```
query {
	c0(
		c0_0: bytelen = 1.0
	)

	d0(
		d0_0: len = 1.0
	)
}
```

**Comment by romshark** [comment]
In GQT 2.0, any operations between `Float` and `Int` values are implicitly coerced to `Float` making `len > 3.14` a valid expression that will be performed as `float64`. In the future, we may throw warnings for constants that don't make much sense like in the aforementioned example.
